### ISSUE TITLE
the libs folder in not standard place

### ISSUE THREAD

**Issue by AxeChen** [hungvu193/Premierleaguenews#1]
i cloned you code ，have found  the libs folder in not standard place. In your code , you make the libs in root directory , so  you need to add this code to use SVG.
```
    compile files('E:/StartUp/PremierLeagueNews/libs/androidsvg-1.2.1.jar')
```
if you move libs folder to app directory, you need not do it.

**Comment by hungvu193** [comment]
oh thank you, my bad, I will fix this soon 👯‍♂️

**Comment by hungvu193** [comment]
fixed!
